sudo: required

services:
  - docker

before_install:
- docker build -t joramk/fc26-haproxy:1.7.9 .
- docker run --privileged --name fc26_haproxy -d joramk/fc26-haproxy:1.7.9

script:
- while sleep 5; do docker top fc26_haproxy ; docker logs fc26_haproxy ; docker ps -a | grep ago ; if [ `docker ps -a | grep '(unhealthy)' | wc -l` != "0" ]; then exit 1; fi ; if [ `docker ps -a | grep '(healthy)' | wc -l` != "0" ]; then exit 0; fi ; if [ `docker ps -a | grep 'starting)' | wc -l` == "0" ]; then exit 1; fi ; done
