#!/bin/bash
if [ ! -z "$HAPROXY_LETSENCRYPT" ]; then
	/usr/bin/certbot renew --pre-hook "systemctl stop haproxy" --post-hook "for dir in $(ls -d /etc/letsencrypt/live/*) ; do cat $dir/privkey.pem $dir/fullchain.pem > $dir/fullkeychain.pem ; done ; systemctl restart haproxy ; sleep 3 ; certbot-ocsp"
else
	exit 2
fi
