#!/bin/bash
if [ -z "$HAPROXY_OCSP" ] || [ -z "$HAPROXY_LETSENCRYPT" ]; then
	exit 2
fi

for OCSP_DOMAIN in /etc/letsencrypt/live/*; do

 openssl ocsp -no_nonce -respout ${OCSP_DOMAIN}/fullkeychain.pem.ocsp \
  -issuer ${OCSP_DOMAIN}/chain.pem \
  -verify_other ${OCSP_DOMAIN}/chain.pem \
  -cert ${OCSP_DOMAIN}/cert.pem \
  -url http://ocsp.int-x3.letsencrypt.org/4 \
  -header "HOST=ocsp.int-x3.letsencrypt.org"

 echo "set ssl ocsp-response $(/usr/bin/base64 -w0 ${OCSP_DOMAIN}/fullkeychain.pem.ocsp)" | /usr/bin/socat stdio /var/run/haproxy.admin
done

exit 0

