#!/bin/bash
for dir in $(ls -d /etc/letsencrypt/live/*); do
        cat $dir/privkey.pem $dir/fullchain.pem > $dir/fullkeychain.pem
done

# Skip reload and OCSP when container gets initialized
if [ -e /firstrun ]; then
	exit 0
fi

systemctl reload haproxy

if [ ! -z "$HAPROXY_LETSENCRYPT_OCSP" && ! -z "$HAPROXY_LETSENCRYPT" ]; then
	sleep 3
	/usr/local/sbin/certbot-ocsp
fi
