#!/bin/bash
if [ -z "$HAPROXY_LETSENCRYPT" ]; then
        echo Lets Encrypt is disabled.
        exit 2
fi

if [ -z "$1" ] || [ -z "$2" ]; then
	echo Usage: certbot-issue domain.tld email@address
	exit 2
fi

certbot certonly --non-interactive --agree-tos --standalone --preferred-challenges http-01 --http-01-port=8888 --domain $1 --email $2 --post-hook="/usr/local/sbin/certbot-posthook"
